site_name: Articul8
site_url: https://www.example.com/docs
repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: nobinRB
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.footer
    - content.footnote.tooltips
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - navigation.indexes
  icon:
    annotation: material/arrow-right-circle
    repo: fontawesome/brands/git-alt
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Light Mode
    - scheme: youtube
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom
      accent: deep orange

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
      accent: yellow
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@james-willett
    - icon: simple/linkedin
      link: https://linkedin.com/in/willettjames
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  version:
    default: stable
    provider: nobin
copyright: Copyright &copy; 2024 James Willett
plugins:
  - glightbox
  - search
# nav:
#   - Home: / # Main index page for the section
#   - Getting started:
#       - pages/page1/index.md # Main index page for the section
#       - Setup:
#           - pages/page1/index.md # First page under Subsection 1
#           - Sub-page 1.1: # Nested sub-subsection under Subsection 1
#               - sub-page 1: pages/page1/page-1.md
#               - sub-page 2: pages/page1/page-2.md
#           - Sub-page 1.2:
#               - sub-page 1: pages/page2/page-1.md
#               - sub-page 2: pages/page2/page-2.md
#       - Extensions:
#           - pages/page2/index.md
#           - Sub-page 2.1:
#               - pages/page2/page-1.md
#               - pages/page2/page-2.md
#   - Reference: pages/page3/index.md # Additional page within the main section

nav:
  - Home: / # Main index page for the section
  - Getting started:
      - pages/page1/first_page.md # Main index page for the section
      - pages/page1/second_page.md # Main index page for the section
      - Sub-page 2.1:
          - pages/page1/sub-page-1/third_page.md
  - Reference: pages/page3/index.md # Additional page within the main section

